CREATE TABLE USER_ROLES
(
    ID            BIGINT
        CONSTRAINT USER_ROLES_ID_NN NOT NULL,
    NAME          VARCHAR,
    DESCRIPTION   VARCHAR,
    CREATING_TIME TIMESTAMP DEFAULT now()
        CONSTRAINT USER_ROLES_CTIME_NN NOT NULL,
    CONSTRAINT USER_ROLES_ID_PK PRIMARY KEY (ID)
);

INSERT INTO USER_ROLES(ID, NAME, DESCRIPTION)
VALUES (1, 'USER', 'User');
INSERT INTO USER_ROLES(ID, NAME, DESCRIPTION)
VALUES (2, 'ADMIN', 'Admin');

CREATE TABLE USERS
(
    ID            BIGINT
        CONSTRAINT USERS_ID_NN NOT NULL,
    CHAT_ID       BIGINT
        CONSTRAINT USERS_CHAT_ID_NN NOT NULL,
    FIRST_NAME    VARCHAR,
    LAST_NAME     VARCHAR,
    USER_NAME     VARCHAR,
    REGISTERED_AT TIMESTAMP,
    USER_ROLE_ID  BIGINT,
    CONSTRAINT USERS_ID_PK PRIMARY KEY (ID),
    CONSTRAINT USERS_CHAT_ID_UN UNIQUE (CHAT_ID),
    CONSTRAINT USERS_ROLE_FK
        FOREIGN KEY (USER_ROLE_ID)
            REFERENCES USER_ROLES (ID)
);

CREATE SEQUENCE user_seq START WITH 1;

CREATE TABLE ADS
(
    ID             BIGINT
        CONSTRAINT ADS_ID_NN NOT NULL,
    AD             VARCHAR,
    DELIVERED_TIME TIMESTAMP,
    CREATING_TIME  TIMESTAMP DEFAULT now()
        CONSTRAINT ADS_CTIME_NN NOT NULL,
    CONSTRAINT ADS_ID_PK PRIMARY KEY (ID)
);

CREATE SEQUENCE ad_seq START WITH 1;





