CREATE TABLE USERS_ARCH
(
    ID            BIGINT
        CONSTRAINT USERS_ID_NN NOT NULL,
    CHAT_ID       BIGINT
        CONSTRAINT USERS_CHAT_ID_NN NOT NULL,
    FIRST_NAME    VARCHAR,
    LAST_NAME     VARCHAR,
    USER_NAME     VARCHAR,
    REGISTERED_AT TIMESTAMP,
    USER_ROLE_ID  BIGINT,
    CONSTRAINT USERS_ARCH_ID_PK PRIMARY KEY (ID)
);

