keycloak:
  auth-server-url: ${KEYCLOAK_AUTH_SERVER_URL}
  realm: ${KEYCLOAK_REALM}

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT}
    org:
      hibernate:
        sql: INFO
        orm:
          jdbc:
            bind: trace
        stat: INFO
        SQL_SLOW: info
        cache: INFO
      springframework:
        security: INFO
    jdbc:
      sqlonly: INFO

server:
  port: 8080

spring:
  application:
    name: TatkoSpringDemoBotBackEndApi
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}?currentSchema=schema1
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # todo Have to be removed
  main:
    allow-circular-references: true
  profiles:
    active: prod
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: http://${KEYCLOAK_ISSUER_URI_HOST}:${KEYCLOAK_ISSUER_URI_PORT}/realms/${KEYCLOAK_REALM}/protocol/openid-connect/certs

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
    oauth:
      client-id: ${KEYCLOAK_CLIENT_ID}
      client-secret: ${KEYCLOAK_CLIENT_SECRET}








