

server:
  port: 8080

#springdoc:
#  swagger-ui:
#    path: docs/ui
#    disable-swagger-default-url: true
#  springdoc.swagger-ui.url=/api/openapi.json


#  springdoc.api-docs.enabled=true
#  springdoc.swagger-ui.enabled=true
#
#  springdoc.swagger-ui.path=/doc/swagger-ui.html

#springdoc:
#  api-docs:
#    path: '/api/admin/v3/api-docs'
#  swagger-ui:
#    path: '/api/admin/swagger-ui.html'
#    url: '/api/admin/v3/api-docs'

spring:
  application:
    name: TatkoSpringDemoBotBackEndApi
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DATABASE}?currentSchema=schema1
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    #driver-class-name: org.postgresql.Driver
#    hikari:
#      allow-pool-suspension: true
  flyway:
    baseline-on-migrate: true
    locations: classpath:db/migration
    enabled: true
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: none
        dialect: org.hibernate.dialect.PostgreSQLDialect
  # todo Have to be removed
  main:
    allow-circular-references: true
  profiles:
    active: prod

logging:
  level:
    root: ${LOGGING_LEVEL_ROOT}
    org:
      hibernate:
        sql: debug
        orm:
          jdbc:
            bind: trace
        stat: debug
        SQL_SLOW: info
        cache: debug
    jdbc:
      sqlonly: INFO







